sudo: required
language: generic 
services: 
    - docker


before_install:
    - docker build -t doors9/docker-react -f Dockerfile.dev .
    
    script:
        - docker run -e CI=true doors9/docker-react npm run test
